// Auto-generated by generate-demo.test.ts (GENERATE_DEMO=1) - do not edit.
// Frozen with both wild cards in the current hand (build-with-wilds flows).
export const demoSnapshotWilds: unknown = {
  "status": "active",
  "value": {
    "playing": {
      "action": "selectingAction"
    }
  },
  "historyValue": {},
  "context": {
    "players": [
      {
        "id": "1",
        "name": "Eliza",
        "color": "red",
        "character": "Eliza Tinsley",
        "money": 0,
        "victoryPoints": 0,
        "income": 0,
        "industryTilesOnMat": {
          "cotton": [
            {
              "tile": {
                "id": "cotton_1",
                "type": "cotton",
                "level": 1,
                "cost": 12,
                "victoryPoints": 5,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 3
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "cotton_2",
                "type": "cotton",
                "level": 2,
                "cost": 14,
                "victoryPoints": 5,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "cotton_3",
                "type": "cotton",
                "level": 3,
                "cost": 16,
                "victoryPoints": 9,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 3
              },
              "quantityAvailable": 3
            },
            {
              "tile": {
                "id": "cotton_4",
                "type": "cotton",
                "level": 4,
                "cost": 18,
                "victoryPoints": 12,
                "incomeSpaces": 2,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 3
              },
              "quantityAvailable": 3
            }
          ],
          "coal": [
            {
              "tile": {
                "id": "coal_1",
                "type": "coal",
                "level": 1,
                "cost": 5,
                "victoryPoints": 1,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 2,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 0
            },
            {
              "tile": {
                "id": "coal_2",
                "type": "coal",
                "level": 2,
                "cost": 7,
                "victoryPoints": 2,
                "incomeSpaces": 7,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 3,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 7,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "coal_3",
                "type": "coal",
                "level": 3,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 4,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "coal_4",
                "type": "coal",
                "level": 4,
                "cost": 10,
                "victoryPoints": 4,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 5,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            }
          ],
          "iron": [
            {
              "tile": {
                "id": "iron_1",
                "type": "iron",
                "level": 1,
                "cost": 5,
                "victoryPoints": 3,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 4,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_2",
                "type": "iron",
                "level": 2,
                "cost": 7,
                "victoryPoints": 5,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 4,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_3",
                "type": "iron",
                "level": 3,
                "cost": 9,
                "victoryPoints": 7,
                "incomeSpaces": 2,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 5,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_4",
                "type": "iron",
                "level": 4,
                "cost": 12,
                "victoryPoints": 9,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 6,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ],
          "manufacturer": [
            {
              "tile": {
                "id": "manufacturer_1",
                "type": "manufacturer",
                "level": 1,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_2",
                "type": "manufacturer",
                "level": 2,
                "cost": 10,
                "victoryPoints": 5,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "manufacturer_3",
                "type": "manufacturer",
                "level": 3,
                "cost": 12,
                "victoryPoints": 4,
                "incomeSpaces": 4,
                "linkScoringIcons": 0,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_4",
                "type": "manufacturer",
                "level": 4,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_5",
                "type": "manufacturer",
                "level": 5,
                "cost": 16,
                "victoryPoints": 8,
                "incomeSpaces": 2,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "manufacturer_6",
                "type": "manufacturer",
                "level": 6,
                "cost": 20,
                "victoryPoints": 7,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_7",
                "type": "manufacturer",
                "level": 7,
                "cost": 16,
                "victoryPoints": 9,
                "incomeSpaces": 4,
                "linkScoringIcons": 0,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_8",
                "type": "manufacturer",
                "level": 8,
                "cost": 20,
                "victoryPoints": 11,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 2,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 2
              },
              "quantityAvailable": 2
            }
          ],
          "pottery": [
            {
              "tile": {
                "id": "pottery_1",
                "type": "pottery",
                "level": 1,
                "cost": 17,
                "victoryPoints": 10,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": true,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_2",
                "type": "pottery",
                "level": 2,
                "cost": 0,
                "victoryPoints": 1,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_3",
                "type": "pottery",
                "level": 3,
                "cost": 22,
                "victoryPoints": 11,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": true,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_4",
                "type": "pottery",
                "level": 4,
                "cost": 0,
                "victoryPoints": 1,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_5",
                "type": "pottery",
                "level": 5,
                "cost": 24,
                "victoryPoints": 20,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": false,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ],
          "brewery": [
            {
              "tile": {
                "id": "brewery_1",
                "type": "brewery",
                "level": 1,
                "cost": 5,
                "victoryPoints": 4,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "brewery_2",
                "type": "brewery",
                "level": 2,
                "cost": 7,
                "victoryPoints": 5,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "brewery_3",
                "type": "brewery",
                "level": 3,
                "cost": 9,
                "victoryPoints": 7,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "brewery_4",
                "type": "brewery",
                "level": 4,
                "cost": 9,
                "victoryPoints": 10,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": false,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ]
        },
        "incomeSpace": 10,
        "hand": [
          {
            "id": "cotton_manufacturer_6",
            "type": "industry",
            "industries": [
              "cotton",
              "manufacturer"
            ]
          },
          {
            "id": "cotton_manufacturer_2",
            "type": "industry",
            "industries": [
              "cotton",
              "manufacturer"
            ]
          },
          {
            "id": "cotton_manufacturer_5",
            "type": "industry",
            "industries": [
              "cotton",
              "manufacturer"
            ]
          },
          {
            "id": "wild_location_1",
            "type": "wild_location"
          },
          {
            "id": "wild_industry_1",
            "type": "wild_industry"
          },
          {
            "id": "leek_2",
            "type": "location",
            "location": "liberec",
            "color": "other"
          },
          {
            "id": "kidderminster_1",
            "type": "location",
            "location": "frydekmistek",
            "color": "other"
          },
          {
            "id": "pottery_2",
            "type": "industry",
            "industries": [
              "pottery"
            ]
          }
        ],
        "links": [],
        "industries": [
          {
            "location": "rosice",
            "type": "coal",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "coal_1",
              "type": "coal",
              "level": 1,
              "cost": 5,
              "victoryPoints": 1,
              "incomeSpaces": 4,
              "linkScoringIcons": 2,
              "coalRequired": 0,
              "ironRequired": 0,
              "beerRequired": 0,
              "beerProduced": 0,
              "coalProduced": 2,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": false,
              "hasLightbulbIcon": false,
              "incomeAdvancement": 4,
              "quantity": 1
            },
            "coalCubesOnTile": 2,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 0
          },
          {
            "location": "brno",
            "type": "cotton",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "cotton_1",
              "type": "cotton",
              "level": 1,
              "cost": 12,
              "victoryPoints": 5,
              "incomeSpaces": 5,
              "linkScoringIcons": 1,
              "coalRequired": 0,
              "ironRequired": 0,
              "beerRequired": 1,
              "beerProduced": 0,
              "coalProduced": 0,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": false,
              "hasLightbulbIcon": false,
              "incomeAdvancement": 5,
              "quantity": 3
            },
            "coalCubesOnTile": 0,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 0
          }
        ]
      },
      {
        "id": "2",
        "name": "Isambard",
        "color": "blue",
        "character": "Isambard Kingdom Brunel",
        "money": 35,
        "victoryPoints": 0,
        "income": -3,
        "industryTilesOnMat": {
          "cotton": [
            {
              "tile": {
                "id": "cotton_1",
                "type": "cotton",
                "level": 1,
                "cost": 12,
                "victoryPoints": 5,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 3
              },
              "quantityAvailable": 3
            },
            {
              "tile": {
                "id": "cotton_2",
                "type": "cotton",
                "level": 2,
                "cost": 14,
                "victoryPoints": 5,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "cotton_3",
                "type": "cotton",
                "level": 3,
                "cost": 16,
                "victoryPoints": 9,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 3
              },
              "quantityAvailable": 3
            },
            {
              "tile": {
                "id": "cotton_4",
                "type": "cotton",
                "level": 4,
                "cost": 18,
                "victoryPoints": 12,
                "incomeSpaces": 2,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 3
              },
              "quantityAvailable": 3
            }
          ],
          "coal": [
            {
              "tile": {
                "id": "coal_1",
                "type": "coal",
                "level": 1,
                "cost": 5,
                "victoryPoints": 1,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 2,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 0
            },
            {
              "tile": {
                "id": "coal_2",
                "type": "coal",
                "level": 2,
                "cost": 7,
                "victoryPoints": 2,
                "incomeSpaces": 7,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 3,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 7,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "coal_3",
                "type": "coal",
                "level": 3,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 4,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "coal_4",
                "type": "coal",
                "level": 4,
                "cost": 10,
                "victoryPoints": 4,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 5,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            }
          ],
          "iron": [
            {
              "tile": {
                "id": "iron_1",
                "type": "iron",
                "level": 1,
                "cost": 5,
                "victoryPoints": 3,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 4,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_2",
                "type": "iron",
                "level": 2,
                "cost": 7,
                "victoryPoints": 5,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 4,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_3",
                "type": "iron",
                "level": 3,
                "cost": 9,
                "victoryPoints": 7,
                "incomeSpaces": 2,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 5,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_4",
                "type": "iron",
                "level": 4,
                "cost": 12,
                "victoryPoints": 9,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 6,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ],
          "manufacturer": [
            {
              "tile": {
                "id": "manufacturer_1",
                "type": "manufacturer",
                "level": 1,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_2",
                "type": "manufacturer",
                "level": 2,
                "cost": 10,
                "victoryPoints": 5,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "manufacturer_3",
                "type": "manufacturer",
                "level": 3,
                "cost": 12,
                "victoryPoints": 4,
                "incomeSpaces": 4,
                "linkScoringIcons": 0,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_4",
                "type": "manufacturer",
                "level": 4,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_5",
                "type": "manufacturer",
                "level": 5,
                "cost": 16,
                "victoryPoints": 8,
                "incomeSpaces": 2,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "manufacturer_6",
                "type": "manufacturer",
                "level": 6,
                "cost": 20,
                "victoryPoints": 7,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_7",
                "type": "manufacturer",
                "level": 7,
                "cost": 16,
                "victoryPoints": 9,
                "incomeSpaces": 4,
                "linkScoringIcons": 0,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_8",
                "type": "manufacturer",
                "level": 8,
                "cost": 20,
                "victoryPoints": 11,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 2,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 2
              },
              "quantityAvailable": 2
            }
          ],
          "pottery": [
            {
              "tile": {
                "id": "pottery_1",
                "type": "pottery",
                "level": 1,
                "cost": 17,
                "victoryPoints": 10,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": true,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_2",
                "type": "pottery",
                "level": 2,
                "cost": 0,
                "victoryPoints": 1,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_3",
                "type": "pottery",
                "level": 3,
                "cost": 22,
                "victoryPoints": 11,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": true,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_4",
                "type": "pottery",
                "level": 4,
                "cost": 0,
                "victoryPoints": 1,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_5",
                "type": "pottery",
                "level": 5,
                "cost": 24,
                "victoryPoints": 20,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": false,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ],
          "brewery": [
            {
              "tile": {
                "id": "brewery_1",
                "type": "brewery",
                "level": 1,
                "cost": 5,
                "victoryPoints": 4,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 2
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "brewery_2",
                "type": "brewery",
                "level": 2,
                "cost": 7,
                "victoryPoints": 5,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "brewery_3",
                "type": "brewery",
                "level": 3,
                "cost": 9,
                "victoryPoints": 7,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "brewery_4",
                "type": "brewery",
                "level": 4,
                "cost": 9,
                "victoryPoints": 10,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": false,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ]
        },
        "incomeSpace": 7,
        "hand": [
          {
            "id": "iron_2",
            "type": "industry",
            "industries": [
              "iron"
            ]
          },
          {
            "id": "pottery_1",
            "type": "industry",
            "industries": [
              "pottery"
            ]
          },
          {
            "id": "wild_location_2",
            "type": "wild_location"
          },
          {
            "id": "wild_industry_2",
            "type": "wild_industry"
          },
          {
            "id": "stoke_1",
            "type": "location",
            "location": "teplice",
            "color": "other"
          },
          {
            "id": "cannock_1",
            "type": "location",
            "location": "rosice",
            "color": "other"
          },
          {
            "id": "brewery_4",
            "type": "industry",
            "industries": [
              "brewery"
            ]
          }
        ],
        "links": [],
        "industries": [
          {
            "location": "prerov",
            "type": "coal",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "coal_1",
              "type": "coal",
              "level": 1,
              "cost": 5,
              "victoryPoints": 1,
              "incomeSpaces": 4,
              "linkScoringIcons": 2,
              "coalRequired": 0,
              "ironRequired": 0,
              "beerRequired": 0,
              "beerProduced": 0,
              "coalProduced": 2,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": false,
              "hasLightbulbIcon": false,
              "incomeAdvancement": 4,
              "quantity": 1
            },
            "coalCubesOnTile": 2,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 0
          },
          {
            "location": "olomouc",
            "type": "brewery",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "brewery_1",
              "type": "brewery",
              "level": 1,
              "cost": 5,
              "victoryPoints": 4,
              "incomeSpaces": 4,
              "linkScoringIcons": 2,
              "coalRequired": 0,
              "ironRequired": 1,
              "beerRequired": 0,
              "beerProduced": 1,
              "coalProduced": 0,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": false,
              "hasLightbulbIcon": false,
              "incomeAdvancement": 4,
              "quantity": 2
            },
            "coalCubesOnTile": 0,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 1
          }
        ]
      },
      {
        "id": "3",
        "name": "George",
        "color": "green",
        "character": "George Stephenson",
        "money": 4,
        "victoryPoints": 0,
        "income": -3,
        "industryTilesOnMat": {
          "cotton": [
            {
              "tile": {
                "id": "cotton_1",
                "type": "cotton",
                "level": 1,
                "cost": 12,
                "victoryPoints": 5,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 3
              },
              "quantityAvailable": 3
            },
            {
              "tile": {
                "id": "cotton_2",
                "type": "cotton",
                "level": 2,
                "cost": 14,
                "victoryPoints": 5,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "cotton_3",
                "type": "cotton",
                "level": 3,
                "cost": 16,
                "victoryPoints": 9,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 3
              },
              "quantityAvailable": 3
            },
            {
              "tile": {
                "id": "cotton_4",
                "type": "cotton",
                "level": 4,
                "cost": 18,
                "victoryPoints": 12,
                "incomeSpaces": 2,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 3
              },
              "quantityAvailable": 3
            }
          ],
          "coal": [
            {
              "tile": {
                "id": "coal_1",
                "type": "coal",
                "level": 1,
                "cost": 5,
                "victoryPoints": 1,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 2,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 0
            },
            {
              "tile": {
                "id": "coal_2",
                "type": "coal",
                "level": 2,
                "cost": 7,
                "victoryPoints": 2,
                "incomeSpaces": 7,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 3,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 7,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "coal_3",
                "type": "coal",
                "level": 3,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 4,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "coal_4",
                "type": "coal",
                "level": 4,
                "cost": 10,
                "victoryPoints": 4,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 5,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            }
          ],
          "iron": [
            {
              "tile": {
                "id": "iron_1",
                "type": "iron",
                "level": 1,
                "cost": 5,
                "victoryPoints": 3,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 4,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_2",
                "type": "iron",
                "level": 2,
                "cost": 7,
                "victoryPoints": 5,
                "incomeSpaces": 3,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 4,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 3,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_3",
                "type": "iron",
                "level": 3,
                "cost": 9,
                "victoryPoints": 7,
                "incomeSpaces": 2,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 5,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "iron_4",
                "type": "iron",
                "level": 4,
                "cost": 12,
                "victoryPoints": 9,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 6,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ],
          "manufacturer": [
            {
              "tile": {
                "id": "manufacturer_1",
                "type": "manufacturer",
                "level": 1,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_2",
                "type": "manufacturer",
                "level": 2,
                "cost": 10,
                "victoryPoints": 5,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "manufacturer_3",
                "type": "manufacturer",
                "level": 3,
                "cost": 12,
                "victoryPoints": 4,
                "incomeSpaces": 4,
                "linkScoringIcons": 0,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_4",
                "type": "manufacturer",
                "level": 4,
                "cost": 8,
                "victoryPoints": 3,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_5",
                "type": "manufacturer",
                "level": 5,
                "cost": 16,
                "victoryPoints": 8,
                "incomeSpaces": 2,
                "linkScoringIcons": 2,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 2,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "manufacturer_6",
                "type": "manufacturer",
                "level": 6,
                "cost": 20,
                "victoryPoints": 7,
                "incomeSpaces": 6,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 6,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_7",
                "type": "manufacturer",
                "level": 7,
                "cost": 16,
                "victoryPoints": 9,
                "incomeSpaces": 4,
                "linkScoringIcons": 0,
                "coalRequired": 1,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "manufacturer_8",
                "type": "manufacturer",
                "level": 8,
                "cost": 20,
                "victoryPoints": 11,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 2,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 2
              },
              "quantityAvailable": 2
            }
          ],
          "pottery": [
            {
              "tile": {
                "id": "pottery_1",
                "type": "pottery",
                "level": 1,
                "cost": 17,
                "victoryPoints": 10,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": true,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 0
            },
            {
              "tile": {
                "id": "pottery_2",
                "type": "pottery",
                "level": 2,
                "cost": 0,
                "victoryPoints": 1,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_3",
                "type": "pottery",
                "level": 3,
                "cost": 22,
                "victoryPoints": 11,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": true,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_4",
                "type": "pottery",
                "level": 4,
                "cost": 0,
                "victoryPoints": 1,
                "incomeSpaces": 1,
                "linkScoringIcons": 1,
                "coalRequired": 1,
                "ironRequired": 0,
                "beerRequired": 1,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 1,
                "quantity": 1
              },
              "quantityAvailable": 1
            },
            {
              "tile": {
                "id": "pottery_5",
                "type": "pottery",
                "level": 5,
                "cost": 24,
                "victoryPoints": 20,
                "incomeSpaces": 5,
                "linkScoringIcons": 1,
                "coalRequired": 2,
                "ironRequired": 0,
                "beerRequired": 2,
                "beerProduced": 0,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": false,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ],
          "brewery": [
            {
              "tile": {
                "id": "brewery_1",
                "type": "brewery",
                "level": 1,
                "cost": 5,
                "victoryPoints": 4,
                "incomeSpaces": 4,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": false,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 4,
                "quantity": 2
              },
              "quantityAvailable": 0
            },
            {
              "tile": {
                "id": "brewery_2",
                "type": "brewery",
                "level": 2,
                "cost": 7,
                "victoryPoints": 5,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "brewery_3",
                "type": "brewery",
                "level": 3,
                "cost": 9,
                "victoryPoints": 7,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": true,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 2
              },
              "quantityAvailable": 2
            },
            {
              "tile": {
                "id": "brewery_4",
                "type": "brewery",
                "level": 4,
                "cost": 9,
                "victoryPoints": 10,
                "incomeSpaces": 5,
                "linkScoringIcons": 2,
                "coalRequired": 0,
                "ironRequired": 1,
                "beerRequired": 0,
                "beerProduced": 1,
                "coalProduced": 0,
                "ironProduced": 0,
                "canBuildInCanalEra": false,
                "canBuildInRailEra": true,
                "hasLightbulbIcon": false,
                "incomeAdvancement": 5,
                "quantity": 1
              },
              "quantityAvailable": 1
            }
          ]
        },
        "incomeSpace": 7,
        "hand": [
          {
            "id": "birmingham_1",
            "type": "location",
            "location": "brno",
            "color": "other"
          },
          {
            "id": "walsall_1",
            "type": "location",
            "location": "blansko",
            "color": "other"
          },
          {
            "id": "kidderminster_2",
            "type": "location",
            "location": "frydekmistek",
            "color": "other"
          },
          {
            "id": "stone_1",
            "type": "location",
            "location": "pardubice",
            "color": "other"
          },
          {
            "id": "wolverhampton_1",
            "type": "location",
            "location": "novyjicin",
            "color": "other"
          },
          {
            "id": "coalbrookdale_2",
            "type": "location",
            "location": "ostrava",
            "color": "other"
          },
          {
            "id": "coalbrookdale_3",
            "type": "location",
            "location": "ostrava",
            "color": "other"
          },
          {
            "id": "brewery_1",
            "type": "industry",
            "industries": [
              "brewery"
            ]
          }
        ],
        "links": [],
        "industries": [
          {
            "location": "blansko",
            "type": "brewery",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "brewery_1",
              "type": "brewery",
              "level": 1,
              "cost": 5,
              "victoryPoints": 4,
              "incomeSpaces": 4,
              "linkScoringIcons": 2,
              "coalRequired": 0,
              "ironRequired": 1,
              "beerRequired": 0,
              "beerProduced": 1,
              "coalProduced": 0,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": false,
              "hasLightbulbIcon": false,
              "incomeAdvancement": 4,
              "quantity": 2
            },
            "coalCubesOnTile": 0,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 1
          },
          {
            "location": "karvina",
            "type": "coal",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "coal_1",
              "type": "coal",
              "level": 1,
              "cost": 5,
              "victoryPoints": 1,
              "incomeSpaces": 4,
              "linkScoringIcons": 2,
              "coalRequired": 0,
              "ironRequired": 0,
              "beerRequired": 0,
              "beerProduced": 0,
              "coalProduced": 2,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": false,
              "hasLightbulbIcon": false,
              "incomeAdvancement": 4,
              "quantity": 1
            },
            "coalCubesOnTile": 2,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 0
          },
          {
            "location": "znojmo",
            "type": "pottery",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "pottery_1",
              "type": "pottery",
              "level": 1,
              "cost": 17,
              "victoryPoints": 10,
              "incomeSpaces": 5,
              "linkScoringIcons": 1,
              "coalRequired": 0,
              "ironRequired": 1,
              "beerRequired": 1,
              "beerProduced": 0,
              "coalProduced": 0,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": true,
              "hasLightbulbIcon": true,
              "incomeAdvancement": 5,
              "quantity": 1
            },
            "coalCubesOnTile": 0,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 0
          },
          {
            "location": "sumperk",
            "type": "brewery",
            "level": 1,
            "flipped": false,
            "tile": {
              "id": "brewery_1",
              "type": "brewery",
              "level": 1,
              "cost": 5,
              "victoryPoints": 4,
              "incomeSpaces": 4,
              "linkScoringIcons": 2,
              "coalRequired": 0,
              "ironRequired": 1,
              "beerRequired": 0,
              "beerProduced": 1,
              "coalProduced": 0,
              "ironProduced": 0,
              "canBuildInCanalEra": true,
              "canBuildInRailEra": false,
              "hasLightbulbIcon": false,
              "incomeAdvancement": 4,
              "quantity": 2
            },
            "coalCubesOnTile": 0,
            "ironCubesOnTile": 0,
            "beerBarrelsOnTile": 1
          }
        ]
      }
    ],
    "currentPlayerIndex": 1,
    "era": "canal",
    "round": 3,
    "actionsRemaining": 1,
    "resources": {
      "coal": 24,
      "iron": 10,
      "beer": 24
    },
    "coalMarket": [
      {
        "price": 1,
        "cubes": 1,
        "maxCubes": 2
      },
      {
        "price": 2,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 3,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 4,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 5,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 6,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 7,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 8,
        "cubes": 0,
        "maxCubes": null
      }
    ],
    "ironMarket": [
      {
        "price": 1,
        "cubes": 0,
        "maxCubes": 2
      },
      {
        "price": 2,
        "cubes": 0,
        "maxCubes": 2
      },
      {
        "price": 3,
        "cubes": 0,
        "maxCubes": 2
      },
      {
        "price": 4,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 5,
        "cubes": 2,
        "maxCubes": 2
      },
      {
        "price": 6,
        "cubes": 0,
        "maxCubes": null
      }
    ],
    "logs": [
      {
        "message": "Game started",
        "type": "system",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Eliza scouted (discarded 3 cards, gained 2 wild cards)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Isambard scouted (discarded 3 cards, gained 2 wild cards)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "George built brewery Level 1 at blansko for £7 (consumed consumed 1 iron from market for £2) using brewery industry",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Eliza collected £0 income",
        "type": "info",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Isambard collected £0 income",
        "type": "info",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "George collected £0 income",
        "type": "info",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Round 1 completed",
        "type": "system",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Eliza built coal Level 1 at rosice for £5 using rosice (other)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Eliza built cotton Level 1 at brno for £12 using brno (other)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.710Z"
      },
      {
        "message": "Isambard built coal Level 1 at prerov for £5 using prerov (other)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "Isambard built brewery Level 1 at olomouc for £7 (consumed consumed 1 iron from market for £2) using olomouc (other)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "George built coal Level 1 at karvina for £5 using karvina (other)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "George took a loan (£30, -3 income) using cotton_manufacturer_1",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "Eliza collected £0 income",
        "type": "info",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "Isambard collected £0 income",
        "type": "info",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "George paid £3 negative income",
        "type": "info",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "Round 2 completed",
        "type": "system",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "George built pottery Level 1 at znojmo for £20 (consumed consumed 1 iron from market for £3) using znojmo (other)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "George built brewery Level 1 at sumperk for £8 (consumed consumed 1 iron from market for £3) using sumperk (other)",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.711Z"
      },
      {
        "message": "Isambard took a loan (£30, -3 income) using iron_3",
        "type": "action",
        "timestamp": "2026-07-15T00:08:26.711Z"
      }
    ],
    "drawPile": [
      {
        "id": "stafford_2",
        "type": "location",
        "location": "jihlava",
        "color": "other"
      },
      {
        "id": "worcester_1",
        "type": "location",
        "location": "zilina",
        "color": "other"
      },
      {
        "id": "iron_4",
        "type": "industry",
        "industries": [
          "iron"
        ]
      },
      {
        "id": "tamworth_1",
        "type": "location",
        "location": "prostejov",
        "color": "other"
      },
      {
        "id": "iron_1",
        "type": "industry",
        "industries": [
          "iron"
        ]
      },
      {
        "id": "cotton_manufacturer_3",
        "type": "industry",
        "industries": [
          "cotton",
          "manufacturer"
        ]
      },
      {
        "id": "dudley_1",
        "type": "location",
        "location": "karvina",
        "color": "other"
      },
      {
        "id": "stafford_1",
        "type": "location",
        "location": "jihlava",
        "color": "other"
      },
      {
        "id": "leek_1",
        "type": "location",
        "location": "liberec",
        "color": "other"
      },
      {
        "id": "coventry_3",
        "type": "location",
        "location": "znojmo",
        "color": "other"
      },
      {
        "id": "worcester_2",
        "type": "location",
        "location": "zilina",
        "color": "other"
      },
      {
        "id": "brewery_2",
        "type": "industry",
        "industries": [
          "brewery"
        ]
      },
      {
        "id": "redditch_1",
        "type": "location",
        "location": "bratislava",
        "color": "other"
      },
      {
        "id": "coalbrookdale_1",
        "type": "location",
        "location": "ostrava",
        "color": "other"
      },
      {
        "id": "birmingham_2",
        "type": "location",
        "location": "brno",
        "color": "other"
      },
      {
        "id": "coventry_2",
        "type": "location",
        "location": "znojmo",
        "color": "other"
      },
      {
        "id": "burton_2",
        "type": "location",
        "location": "prerov",
        "color": "other"
      },
      {
        "id": "coal_2",
        "type": "industry",
        "industries": [
          "coal"
        ]
      },
      {
        "id": "stoke_2",
        "type": "location",
        "location": "teplice",
        "color": "other"
      }
    ],
    "discardPile": [
      {
        "id": "brewery_3",
        "type": "industry",
        "industries": [
          "brewery"
        ]
      },
      {
        "id": "coal_1",
        "type": "industry",
        "industries": [
          "coal"
        ]
      },
      {
        "id": "stone_2",
        "type": "location",
        "location": "pardubice",
        "color": "other"
      },
      {
        "id": "wolverhampton_2",
        "type": "location",
        "location": "novyjicin",
        "color": "other"
      },
      {
        "id": "stoke_3",
        "type": "location",
        "location": "teplice",
        "color": "other"
      },
      {
        "id": "cotton_manufacturer_4",
        "type": "industry",
        "industries": [
          "cotton",
          "manufacturer"
        ]
      },
      {
        "id": "brewery_5",
        "type": "industry",
        "industries": [
          "brewery"
        ]
      },
      {
        "id": "cannock_2",
        "type": "location",
        "location": "rosice",
        "color": "other"
      },
      {
        "id": "birmingham_3",
        "type": "location",
        "location": "brno",
        "color": "other"
      },
      {
        "id": "burton_1",
        "type": "location",
        "location": "prerov",
        "color": "other"
      },
      {
        "id": "nuneaton_1",
        "type": "location",
        "location": "olomouc",
        "color": "other"
      },
      {
        "id": "dudley_2",
        "type": "location",
        "location": "karvina",
        "color": "other"
      },
      {
        "id": "cotton_manufacturer_1",
        "type": "industry",
        "industries": [
          "cotton",
          "manufacturer"
        ]
      },
      {
        "id": "coventry_1",
        "type": "location",
        "location": "znojmo",
        "color": "other"
      },
      {
        "id": "uttoxeter_1",
        "type": "location",
        "location": "sumperk",
        "color": "other"
      },
      {
        "id": "iron_3",
        "type": "industry",
        "industries": [
          "iron"
        ]
      }
    ],
    "wildLocationPile": [],
    "wildIndustryPile": [],
    "selectedCard": null,
    "selectedCardsForScout": [],
    "spentMoney": 28,
    "playerSpending": {
      "3": 28
    },
    "turnOrder": [
      "3",
      "2",
      "1"
    ],
    "isFinalRound": false,
    "selectedLink": null,
    "selectedSecondLink": null,
    "selectedLocation": null,
    "selectedIndustryTile": {
      "id": "iron_1",
      "type": "iron",
      "level": 1,
      "cost": 5,
      "victoryPoints": 3,
      "incomeSpaces": 3,
      "linkScoringIcons": 1,
      "coalRequired": 1,
      "ironRequired": 0,
      "beerRequired": 0,
      "beerProduced": 0,
      "coalProduced": 0,
      "ironProduced": 4,
      "canBuildInCanalEra": true,
      "canBuildInRailEra": false,
      "hasLightbulbIcon": false,
      "incomeAdvancement": 3,
      "quantity": 1
    },
    "selectedTilesForDevelop": [],
    "merchants": [
      {
        "location": "krakow",
        "industryIcons": [
          "manufacturer"
        ],
        "bonusType": "victoryPoints",
        "bonusValue": 4,
        "hasBeer": true
      },
      {
        "location": "budapest",
        "industryIcons": [
          "cotton",
          "manufacturer",
          "pottery"
        ],
        "bonusType": "develop",
        "bonusValue": 1,
        "hasBeer": true
      },
      {
        "location": "budapest",
        "industryIcons": [
          "cotton"
        ],
        "bonusType": "develop",
        "bonusValue": 1,
        "hasBeer": true
      },
      {
        "location": "vienna",
        "industryIcons": [],
        "bonusType": "income",
        "bonusValue": 2,
        "hasBeer": false
      },
      {
        "location": "vienna",
        "industryIcons": [
          "pottery"
        ],
        "bonusType": "income",
        "bonusValue": 2,
        "hasBeer": true
      },
      {
        "location": "prague",
        "industryIcons": [],
        "bonusType": "money",
        "bonusValue": 5,
        "hasBeer": false
      },
      {
        "location": "prague",
        "industryIcons": [
          "cotton",
          "manufacturer",
          "pottery"
        ],
        "bonusType": "money",
        "bonusValue": 5,
        "hasBeer": true
      }
    ],
    "salesMadeThisAction": 0,
    "eraEndPending": false,
    "winners": null,
    "lastError": null,
    "errorContext": null
  },
  "children": {}
}
